table_main:

        ; 00-0f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 10-1f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 20-2f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 30-3f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 40-4f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 50-5f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 60-6f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 70-7f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 80-8f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; 90-9f
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; a0-af
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; b0-bf
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; c0-cf
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; d0-df
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; e0-ef
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        ; f0-ff
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop
        dw instr_nop

cycles_main:

        db 4, 10,  7,  6,  4,  4,  7,  4,  4, 11,  7,  6,  4,  4,  7,  4
        db 8, 10,  7,  6,  4,  4,  7,  4, 12, 11,  7,  6,  4,  4,  7,  4
        db 7, 10, 16,  6,  4,  4,  7,  4,  7, 11, 16,  6,  4,  4,  7,  4
        db 7, 10, 13,  6, 11, 11, 10,  4,  7, 11, 13,  6,  4,  4,  7,  4
        db 4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4
        db 4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4
        db 4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4
        db 7,  7,  7,  7,  7,  7,  4,  7,  4,  4,  4,  4,  4,  4,  7,  4
        db 4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4
        db 4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4
        db 4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4
        db 4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4
        db 5, 10, 10, 10, 10, 11,  7, 11,  5, 10, 10,  0, 10, 17,  7, 11
        db 5, 10, 10, 11, 10, 11,  7, 11,  5,  4, 10, 11, 10,  0,  7, 11
        db 5, 10, 10, 19, 10, 11,  7, 11,  5,  4, 10,  4, 10,  0,  7, 11
        db 5, 10, 10,  4, 10, 11,  7, 11,  5,  6, 10,  4, 10,  0,  7, 11
