table_main:

        ; 00-0f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 10-1f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 20-2f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 30-3f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 40-4f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 50-5f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 60-6f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 70-7f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 80-8f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; 90-9f
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; a0-af
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; b0-bf
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; c0-cf
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; d0-df
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; e0-ef
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        ; f0-ff
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
        dw      instr_nop
